<a href="https://colab.research.google.com/github/Apoorvmittal11/23-CS-072-DL-LAB-EXPERIMENT/blob/main/DL%20EXPERIMENT%201/23_CS_072_DL_EXPERIMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Experiment -1**

Fundamentals of tensor operations using Pytorch and Numpy.

In [1]:
import numpy as np
import torch

print("NumPy version:", np.__version__)
print("PyTorch version:", torch.__version__)

NumPy version: 2.0.2
PyTorch version: 2.9.0+cpu


Why tensors?

In [16]:
import time
N = 1000000

list1 = list(range(N))
list2 = list(range(N))

tensor1 = torch.arange(N)
tensor2 = torch.arange(N)

start = time.time()
list_result = [list1[i] * list2[i] for i in range(N)]
end = time.time()

print("List multiplication time:", end - start, "seconds")

start = time.time()
tensor_result = tensor1 * tensor2
end = time.time()

print("Tensor multiplication time:", end - start, "seconds")

List multiplication time: 0.12247109413146973 seconds
Tensor multiplication time: 0.008048295974731445 seconds


Create 1D,2D and 3D tensors using Pytorch and Numpy.

In [17]:
#numpy
np_1d = np.array([1, 2, 3])

np_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

np_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(np_1d)
print(np_2d)
print(np_3d)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#pytorch
torch_1d = torch.tensor([1, 2, 3])

torch_2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

torch_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(torch_1d)
print(torch_2d)
print(torch_3d)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


Show basic operations : Element wise operations.

In [4]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])
print(a_np + b_np)
print(a_np * b_np)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
[5 7 9]
[ 4 10 18]


Indexing and slicing operations( Boolean Masking, extracting subtensor.. etc)

In [19]:
print("Basic Indexing")
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(x[0])
print(x[:, 1])
print(x[1, 2])

print("\nExtracting Sub-tensors")
print(x[0:2, 1:3])

print("\nBoolean Masking")
y = torch.tensor([1, 5, 10, 15, 20])

mask = y > 10
print(mask)
print(y[mask])
y_np = np.array([1, 5, 10, 15, 20])
print(y_np[y_np > 10])


Basic Indexing
tensor([10, 20, 30])
tensor([20, 50])
tensor(60)

Extracting Sub-tensors
tensor([[20, 30],
        [50, 60]])

Boolean Masking
tensor([False, False, False,  True,  True])
tensor([15, 20])
[15 20]


Use .view, .reshape .unsqueeze and squeeze function in pytorch

In [7]:
#.view()
t = torch.arange(12)
print(t)

t2 = t.view(3, 4)
print(t2)

#.reshape()
t3 = t.reshape(4, 3)
print(t3)

#.unsqueeze()
a = torch.tensor([1, 2, 3])
print(a.shape)

b = a.unsqueeze(0)
print(b.shape)

c = a.unsqueeze(1)
print(c.shape)

#.squeeze()
d = torch.tensor([[1, 2, 3]])
print(d.shape)

print(d.squeeze().shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([1, 3])
torch.Size([3])


Compare with .reshape in numpy

In [8]:
np_arr = np.arange(12)
np_reshaped = np_arr.reshape(3, 4)
print(np_reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Broadcasting

In [10]:
print("pytorch")
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y = torch.tensor([10, 20, 30])

print(x + y)

print("numpy")
x_np = np.array([[1, 2, 3],
                 [4, 5, 6]])

y_np = np.array([10, 20, 30])

print(x_np + y_np)


pytorch
tensor([[11, 22, 33],
        [14, 25, 36]])
numpy
[[11 22 33]
 [14 25 36]]


In place vs out of place operations

In [11]:
#out of place operations
a = torch.tensor([1, 2, 3])
b = a + 5

print(a)
print(b)

#in of place operations
a = torch.tensor([1, 2, 3])
a.add_(5)

print(a)

tensor([1, 2, 3])
tensor([6, 7, 8])
tensor([6, 7, 8])
